/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ankit Swami
 */
public class Editdetail extends javax.swing.JFrame {

    /**
     * Creates new form Editdetail
     */
    public Editdetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgmaritalstatus = new javax.swing.ButtonGroup();
        bggender = new javax.swing.ButtonGroup();
        bg10 = new javax.swing.ButtonGroup();
        bg12 = new javax.swing.ButtonGroup();
        bgdob = new javax.swing.ButtonGroup();
        bgcaste = new javax.swing.ButtonGroup();
        bgdiploma = new javax.swing.ButtonGroup();
        bgphyical = new javax.swing.ButtonGroup();
        bgmigration = new javax.swing.ButtonGroup();
        bgother = new javax.swing.ButtonGroup();
        bgprogramme = new javax.swing.ButtonGroup();
        bgunder = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lbwall = new javax.swing.JLabel();
        bt3home = new javax.swing.JButton();
        bt3back = new javax.swing.JButton();
        bt3existstd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rd3btech = new javax.swing.JRadioButton();
        rd3mtech = new javax.swing.JRadioButton();
        cb3branch = new javax.swing.JComboBox();
        cb3rank = new javax.swing.JComboBox();
        tx3add = new javax.swing.JTextField();
        rd3sfs = new javax.swing.JRadioButton();
        rd3tfws = new javax.swing.JRadioButton();
        tx3scholar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tx3rank = new javax.swing.JTextField();
        tx3name = new javax.swing.JTextField();
        tx3mname = new javax.swing.JTextField();
        tx3fname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tx3contact = new javax.swing.JTextField();
        tx3city = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tx3pincode = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cb3state = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        cb3blood = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        tx3email = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rd3married = new javax.swing.JRadioButton();
        rd3unmarried = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        rd3male = new javax.swing.JRadioButton();
        rd3female = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        cb3religion = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        chb3ph = new javax.swing.JCheckBox();
        chb3ex = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        tx3occupation = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tx3income = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tx3board10 = new javax.swing.JTextField();
        tx3yop10 = new javax.swing.JTextField();
        tx3sub10 = new javax.swing.JTextField();
        tx3marks10 = new javax.swing.JTextField();
        tx3sub12 = new javax.swing.JTextField();
        tx3board12 = new javax.swing.JTextField();
        tx3yop12 = new javax.swing.JTextField();
        tx3yopug = new javax.swing.JTextField();
        tx3subug = new javax.swing.JTextField();
        tx3boardug = new javax.swing.JTextField();
        tx3marks12 = new javax.swing.JTextField();
        tx3marksug = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        rd3no10 = new javax.swing.JRadioButton();
        rd3nodob = new javax.swing.JRadioButton();
        rd3no12 = new javax.swing.JRadioButton();
        rd3yes10 = new javax.swing.JRadioButton();
        rd3yes12 = new javax.swing.JRadioButton();
        rd3yescaste = new javax.swing.JRadioButton();
        rd3yesdob = new javax.swing.JRadioButton();
        rd3nocaste = new javax.swing.JRadioButton();
        rd3yesmarksheet = new javax.swing.JRadioButton();
        rd3nomarksheet = new javax.swing.JRadioButton();
        rd3yesph = new javax.swing.JRadioButton();
        rd3noph = new javax.swing.JRadioButton();
        rd3yesmigration = new javax.swing.JRadioButton();
        rd3nomigration = new javax.swing.JRadioButton();
        rd3yesother = new javax.swing.JRadioButton();
        rd3noother = new javax.swing.JRadioButton();
        bt3update = new javax.swing.JButton();
        bt3browse = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1300, 2700));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(1466, 2800));

        bt3home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toy/anagrams/lib/homeicon.png"))); // NOI18N
        bt3home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3homeActionPerformed(evt);
            }
        });

        bt3back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toy/anagrams/lib/backicon.png"))); // NOI18N

        bt3existstd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toy/anagrams/lib/existicon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel2.setText("Student Details");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel3.setText("Programme :-");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setText("Branch :-");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel5.setText("Scholar No. :-");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel6.setText("Rank           :-");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel7.setText("Under :-");

        bgprogramme.add(rd3btech);
        rd3btech.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        rd3btech.setText("B.Tech");
        rd3btech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3btechActionPerformed(evt);
            }
        });

        bgprogramme.add(rd3mtech);
        rd3mtech.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        rd3mtech.setText("M.Tech");
        rd3mtech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3mtechActionPerformed(evt);
            }
        });

        cb3branch.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        cb3branch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "ECE", "EE(ISHIFT)", "ME(ISHIFT)", "EE(IISHIFT)", "ME(IISHIFT)", "IT", "EICE", "CIVIL ", "POWERSYSTEM (M TECH)", "COMPUTER SCIENCE (M TECH)", "THERMAL(M TECH)" }));
        cb3branch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3branchActionPerformed(evt);
            }
        });

        cb3rank.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        cb3rank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT", "JEE", "RPET", "REAP" }));
        cb3rank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3rankActionPerformed(evt);
            }
        });

        bgunder.add(rd3sfs);
        rd3sfs.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        rd3sfs.setText("SFS");
        rd3sfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3sfsActionPerformed(evt);
            }
        });

        bgunder.add(rd3tfws);
        rd3tfws.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        rd3tfws.setText("TFWS");
        rd3tfws.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3tfwsActionPerformed(evt);
            }
        });

        tx3scholar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx3scholarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel1.setText("1.Personal Details");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel9.setText("Contact               :-");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel10.setText("Mother's Name  :-");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel11.setText("Father's Name         :-");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel12.setText("Address                    :-");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toy/anagrams/lib/project image/user_tour.jpg"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tx3rank.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tx3name.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tx3name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx3nameActionPerformed(evt);
            }
        });

        tx3mname.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tx3mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx3mnameActionPerformed(evt);
            }
        });

        tx3fname.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel14.setText("Name                 :-");

        tx3contact.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tx3contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx3contactActionPerformed(evt);
            }
        });

        tx3city.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tx3city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx3cityActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel15.setText("City                          :-");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel16.setText("State                        :-");

        tx3pincode.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tx3pincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx3pincodeActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel17.setText("Pin Code                 :-");

        cb3state.setForeground(new java.awt.Color(51, 51, 0));
        cb3state.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Andhra Pradesh", " Arunachal Pradesh", "Assam", "Bihar\t", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "JharkhandKarnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", " " }));
        cb3state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3stateActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel18.setText("Blood Group           :-");

        cb3blood.setForeground(new java.awt.Color(51, 51, 0));
        cb3blood.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "AB+", "AB-", "O+", "0--", " " }));
        cb3blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3bloodActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel19.setText("D.O.B                 :-");

        tx3email.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        tx3email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx3emailActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel20.setText("E-Mail               :-");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel21.setText("Marital Status    :-");

        bgmaritalstatus.add(rd3married);
        rd3married.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3married.setText("Married");
        rd3married.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3marriedActionPerformed(evt);
            }
        });

        bgmaritalstatus.add(rd3unmarried);
        rd3unmarried.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3unmarried.setText("Unmarried");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel22.setText("Gender    :-");

        bggender.add(rd3male);
        rd3male.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3male.setText("Male");
        rd3male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3maleActionPerformed(evt);
            }
        });

        bggender.add(rd3female);
        rd3female.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3female.setText("Female");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel23.setText("Religion             :-");

        cb3religion.setForeground(new java.awt.Color(51, 51, 0));
        cb3religion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HINDU", "MUSLIM", "SIKH", "CHRISTIAN", "JAIN", "OTHER" }));
        cb3religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3religionActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel24.setText("If Std. Belongs To    :-");

        chb3ph.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        chb3ph.setText("P.H");
        chb3ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb3phActionPerformed(evt);
            }
        });

        chb3ex.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        chb3ex.setText("Ex Serviceman");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel25.setText("Parent's Occuption :-");

        tx3occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx3occupationActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel26.setText("Parent's Income :-");

        tx3income.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx3incomeActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel27.setText("2.List Of Enclosures(Attested Photocopy)");

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel28.setText("Examination");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel29.setText("Board/University");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel30.setText("Subjects");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel31.setText("Year Of Passing");
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel32.setText("10 th ");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel33.setText("% Marks/CGPA");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel34.setText("12th");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel35.setText("Detail Of UG Degree");

        tx3board10.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tx3yop10.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tx3sub10.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tx3marks10.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tx3sub12.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tx3board12.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tx3yop12.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tx3yopug.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tx3subug.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tx3boardug.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tx3marks12.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        tx3marksug.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel36.setText("2.Educational Details");

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel37.setText(" D.O.B Certificate      :-");

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel38.setText("12th                           :-");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel39.setText("10 th                          :-");

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel40.setText("Caste Certificate       :-");

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel41.setText("Diploma/B.Tech Marksheet      :-");

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel42.setText("PH/Ex Serviceman Certificate  :-");

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel43.setText("Migration/TC                            :-");

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel44.setText("Other(if any)                             :-");

        bg10.add(rd3no10);
        rd3no10.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3no10.setText("No");
        rd3no10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3no10ActionPerformed(evt);
            }
        });

        bgdob.add(rd3nodob);
        rd3nodob.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3nodob.setText("No");
        rd3nodob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3nodobActionPerformed(evt);
            }
        });

        rd3no12.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3no12.setText("No");

        bg10.add(rd3yes10);
        rd3yes10.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3yes10.setText("Yes");
        rd3yes10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3yes10ActionPerformed(evt);
            }
        });

        rd3yes12.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3yes12.setText("Yes");
        rd3yes12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3yes12ActionPerformed(evt);
            }
        });

        rd3yescaste.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3yescaste.setText("Yes");
        rd3yescaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3yescasteActionPerformed(evt);
            }
        });

        bgdob.add(rd3yesdob);
        rd3yesdob.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3yesdob.setText("Yes");
        rd3yesdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3yesdobActionPerformed(evt);
            }
        });

        rd3nocaste.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3nocaste.setText("No");
        rd3nocaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3nocasteActionPerformed(evt);
            }
        });

        bgdiploma.add(rd3yesmarksheet);
        rd3yesmarksheet.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3yesmarksheet.setText("Yes");
        rd3yesmarksheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3yesmarksheetActionPerformed(evt);
            }
        });

        bgdiploma.add(rd3nomarksheet);
        rd3nomarksheet.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3nomarksheet.setText("No");
        rd3nomarksheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3nomarksheetActionPerformed(evt);
            }
        });

        bgphyical.add(rd3yesph);
        rd3yesph.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3yesph.setText("Yes");
        rd3yesph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3yesphActionPerformed(evt);
            }
        });

        bgphyical.add(rd3noph);
        rd3noph.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3noph.setText("No");
        rd3noph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3nophActionPerformed(evt);
            }
        });

        bgmigration.add(rd3yesmigration);
        rd3yesmigration.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3yesmigration.setText("Yes");
        rd3yesmigration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3yesmigrationActionPerformed(evt);
            }
        });

        bgmigration.add(rd3nomigration);
        rd3nomigration.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3nomigration.setText("No");
        rd3nomigration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3nomigrationActionPerformed(evt);
            }
        });

        bgother.add(rd3yesother);
        rd3yesother.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3yesother.setText("Yes");
        rd3yesother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3yesotherActionPerformed(evt);
            }
        });

        bgother.add(rd3noother);
        rd3noother.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        rd3noother.setText("No");
        rd3noother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd3nootherActionPerformed(evt);
            }
        });

        bt3update.setBackground(new java.awt.Color(102, 153, 255));
        bt3update.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        bt3update.setText("Update");
        bt3update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3updateActionPerformed(evt);
            }
        });

        bt3browse.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        bt3browse.setText("Browse");
        bt3browse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tx3name, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rd3married, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rd3unmarried, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rd3male, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(chb3ph)))
                                        .addGap(58, 58, 58)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chb3ex)
                                            .addComponent(rd3female, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tx3occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(259, 259, 259)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rd3yes10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rd3yescaste, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rd3no10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(rd3no12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tx3email, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20))
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(tx3contact, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(tx3mname, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tx3city, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(332, 332, 332)
                                                .addComponent(tx3pincode, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(337, 337, 337)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cb3state, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cb3blood, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cb3religion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tx3income, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(331, 331, 331)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tx3fname, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tx3add, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(118, 118, 118)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(150, 150, 150)
                                        .addComponent(cb3rank, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(tx3rank, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(rd3sfs, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(rd3tfws, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(234, 234, 234)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tx3sub10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tx3sub12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tx3subug, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(31, 31, 31)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tx3board10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel29)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(62, 62, 62)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(tx3yop10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(tx3yop12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(tx3yopug, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel15)
                                                            .addComponent(jLabel12)
                                                            .addComponent(jLabel11)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                                                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel43)
                                                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(tx3board12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tx3boardug, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rd3yesph, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rd3noph, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rd3yesmarksheet, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rd3nomarksheet, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rd3yesmigration, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rd3nomigration, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rd3yesother, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rd3noother, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tx3marks10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tx3marks12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tx3marksug, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 245, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(580, 580, 580)
                        .addComponent(bt3home, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(bt3existstd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(bt3back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(rd3btech, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(rd3mtech, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cb3branch, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(tx3scholar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel40)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel37)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rd3yes12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rd3yesdob, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rd3nocaste, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rd3nodob, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbwall))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(588, 588, 588)
                        .addComponent(bt3update, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt3browse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbwall)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt3home, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt3existstd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt3back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd3btech, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(rd3mtech, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cb3branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx3scholar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rd3sfs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rd3tfws, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb3rank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(tx3rank, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(tx3fname, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx3name, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(bt3browse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx3mname, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx3add, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tx3city, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tx3contact, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tx3pincode, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tx3email, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb3state, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rd3married, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rd3unmarried, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cb3blood, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rd3male, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rd3female, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chb3ph, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(chb3ex)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cb3religion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tx3occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tx3income, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(424, 424, 424))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(614, 614, 614)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(tx3sub10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx3board10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx3yop10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx3marks10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(tx3sub12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx3board12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx3yop12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx3marks12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(tx3subug, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx3boardug, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx3yopug, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx3marksug, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(116, 116, 116)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(rd3no10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rd3yes10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41)
                            .addComponent(rd3yesmarksheet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rd3nomarksheet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rd3yes12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel38)
                                .addComponent(rd3no12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel42)
                                .addComponent(rd3yesph, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rd3noph, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(rd3nodob, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rd3yesdob, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(jLabel40))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rd3yescaste, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rd3nocaste, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(rd3yesmigration, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rd3nomigration, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rd3yesother, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rd3noother, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(77, 77, 77)
                .addComponent(bt3update, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(687, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1049, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt3homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt3homeActionPerformed

    private void rd3btechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3btechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3btechActionPerformed

    private void rd3mtechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3mtechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3mtechActionPerformed

    private void cb3branchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3branchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb3branchActionPerformed

    private void cb3rankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3rankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb3rankActionPerformed

    private void rd3sfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3sfsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3sfsActionPerformed

    private void rd3tfwsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3tfwsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3tfwsActionPerformed

    private void tx3scholarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx3scholarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx3scholarActionPerformed

    private void tx3nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx3nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx3nameActionPerformed

    private void tx3mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx3mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx3mnameActionPerformed

    private void tx3contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx3contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx3contactActionPerformed

    private void tx3cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx3cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx3cityActionPerformed

    private void tx3pincodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx3pincodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx3pincodeActionPerformed

    private void cb3stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb3stateActionPerformed

    private void cb3bloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3bloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb3bloodActionPerformed

    private void tx3emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx3emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx3emailActionPerformed

    private void rd3marriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3marriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3marriedActionPerformed

    private void rd3maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3maleActionPerformed

    private void cb3religionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3religionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb3religionActionPerformed

    private void chb3phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb3phActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chb3phActionPerformed

    private void tx3occupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx3occupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx3occupationActionPerformed

    private void tx3incomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx3incomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx3incomeActionPerformed

    private void rd3no10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3no10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3no10ActionPerformed

    private void rd3nodobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3nodobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3nodobActionPerformed

    private void rd3yes10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3yes10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3yes10ActionPerformed

    private void rd3yes12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3yes12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3yes12ActionPerformed

    private void rd3yescasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3yescasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3yescasteActionPerformed

    private void rd3yesdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3yesdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3yesdobActionPerformed

    private void rd3nocasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3nocasteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3nocasteActionPerformed

    private void rd3yesmarksheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3yesmarksheetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3yesmarksheetActionPerformed

    private void rd3nomarksheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3nomarksheetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3nomarksheetActionPerformed

    private void rd3yesphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3yesphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3yesphActionPerformed

    private void rd3nophActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3nophActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3nophActionPerformed

    private void rd3yesmigrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3yesmigrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3yesmigrationActionPerformed

    private void rd3nomigrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3nomigrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3nomigrationActionPerformed

    private void rd3yesotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3yesotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3yesotherActionPerformed

    private void rd3nootherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd3nootherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd3nootherActionPerformed

    private void bt3updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt3updateActionPerformed

    private void bt3browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3browseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt3browseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editdetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg10;
    private javax.swing.ButtonGroup bg12;
    private javax.swing.ButtonGroup bgcaste;
    private javax.swing.ButtonGroup bgdiploma;
    private javax.swing.ButtonGroup bgdob;
    private javax.swing.ButtonGroup bggender;
    private javax.swing.ButtonGroup bgmaritalstatus;
    private javax.swing.ButtonGroup bgmigration;
    private javax.swing.ButtonGroup bgother;
    private javax.swing.ButtonGroup bgphyical;
    private javax.swing.ButtonGroup bgprogramme;
    private javax.swing.ButtonGroup bgunder;
    private javax.swing.JButton bt3back;
    private javax.swing.JButton bt3browse;
    private javax.swing.JButton bt3existstd;
    private javax.swing.JButton bt3home;
    private javax.swing.JButton bt3update;
    private javax.swing.JComboBox cb3blood;
    private javax.swing.JComboBox cb3branch;
    private javax.swing.JComboBox cb3rank;
    private javax.swing.JComboBox cb3religion;
    private javax.swing.JComboBox cb3state;
    private javax.swing.JCheckBox chb3ex;
    private javax.swing.JCheckBox chb3ph;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbwall;
    private javax.swing.JRadioButton rd3btech;
    private javax.swing.JRadioButton rd3female;
    private javax.swing.JRadioButton rd3male;
    private javax.swing.JRadioButton rd3married;
    private javax.swing.JRadioButton rd3mtech;
    private javax.swing.JRadioButton rd3no10;
    private javax.swing.JRadioButton rd3no12;
    private javax.swing.JRadioButton rd3nocaste;
    private javax.swing.JRadioButton rd3nodob;
    private javax.swing.JRadioButton rd3nomarksheet;
    private javax.swing.JRadioButton rd3nomigration;
    private javax.swing.JRadioButton rd3noother;
    private javax.swing.JRadioButton rd3noph;
    private javax.swing.JRadioButton rd3sfs;
    private javax.swing.JRadioButton rd3tfws;
    private javax.swing.JRadioButton rd3unmarried;
    private javax.swing.JRadioButton rd3yes10;
    private javax.swing.JRadioButton rd3yes12;
    private javax.swing.JRadioButton rd3yescaste;
    private javax.swing.JRadioButton rd3yesdob;
    private javax.swing.JRadioButton rd3yesmarksheet;
    private javax.swing.JRadioButton rd3yesmigration;
    private javax.swing.JRadioButton rd3yesother;
    private javax.swing.JRadioButton rd3yesph;
    private javax.swing.JTextField tx3add;
    private javax.swing.JTextField tx3board10;
    private javax.swing.JTextField tx3board12;
    private javax.swing.JTextField tx3boardug;
    private javax.swing.JTextField tx3city;
    private javax.swing.JTextField tx3contact;
    private javax.swing.JTextField tx3email;
    private javax.swing.JTextField tx3fname;
    private javax.swing.JTextField tx3income;
    private javax.swing.JTextField tx3marks10;
    private javax.swing.JTextField tx3marks12;
    private javax.swing.JTextField tx3marksug;
    private javax.swing.JTextField tx3mname;
    private javax.swing.JTextField tx3name;
    private javax.swing.JTextField tx3occupation;
    private javax.swing.JTextField tx3pincode;
    private javax.swing.JTextField tx3rank;
    private javax.swing.JTextField tx3scholar;
    private javax.swing.JTextField tx3sub10;
    private javax.swing.JTextField tx3sub12;
    private javax.swing.JTextField tx3subug;
    private javax.swing.JTextField tx3yop10;
    private javax.swing.JTextField tx3yop12;
    private javax.swing.JTextField tx3yopug;
    // End of variables declaration//GEN-END:variables
}
