
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author annu
 */
public class examsectiondetail extends javax.swing.JFrame {

    /**
     * Creates new form examsectiondetail
     */
    public examsectiondetail() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        panelmtech = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        ISMainchk = new javax.swing.JCheckBox();
        IISMainchk = new javax.swing.JCheckBox();
        IIISMainchk = new javax.swing.JCheckBox();
        IVSMainchk = new javax.swing.JCheckBox();
        ISBackchk = new javax.swing.JCheckBox();
        IISBackchk = new javax.swing.JCheckBox();
        IIISBackchk = new javax.swing.JCheckBox();
        IVSBackchk = new javax.swing.JCheckBox();
        ISRbchk = new javax.swing.JCheckBox();
        IISRbchk = new javax.swing.JCheckBox();
        IIISRbchk = new javax.swing.JCheckBox();
        IVSRbchk = new javax.swing.JCheckBox();
        panelbtech = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        VSMainchk = new javax.swing.JCheckBox();
        VISMainchk = new javax.swing.JCheckBox();
        VIISMainchk = new javax.swing.JCheckBox();
        VIIISMainchk = new javax.swing.JCheckBox();
        VISBackchk = new javax.swing.JCheckBox();
        VSBackchk = new javax.swing.JCheckBox();
        VIISBackchk = new javax.swing.JCheckBox();
        VIIISBackchk = new javax.swing.JCheckBox();
        VSRbchk = new javax.swing.JCheckBox();
        VISRbchk = new javax.swing.JCheckBox();
        VIISRbchk = new javax.swing.JCheckBox();
        VIIISRbchk = new javax.swing.JCheckBox();
        updateDataBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        degchk = new javax.swing.JCheckBox();
        procertychk = new javax.swing.JCheckBox();
        updateDataBtn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toy/anagrams/lib/homeicon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toy/anagrams/lib/backicon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel51.setText("Details of Marksheets");

        jLabel52.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel52.setText("Semester");

        jLabel53.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel53.setText("Back");

        jLabel54.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel54.setText("I Semester");

        jLabel55.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel55.setText("IV Semester");

        jLabel56.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel56.setText("II Semester");

        jLabel57.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel57.setText("III Semester");

        jLabel58.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel58.setText(" Main");

        jLabel59.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel59.setText("Reback");

        ISMainchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISMainchkActionPerformed(evt);
            }
        });

        IISMainchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IISMainchkActionPerformed(evt);
            }
        });

        ISBackchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBackchkActionPerformed(evt);
            }
        });

        ISRbchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISRbchkActionPerformed(evt);
            }
        });

        jLabel60.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel60.setText("V Semester");

        jLabel61.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel61.setText("VII Semester");

        jLabel62.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel62.setText("VI Semester");

        jLabel63.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel63.setText("VIII Semester");

        VSRbchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VSRbchkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelbtechLayout = new javax.swing.GroupLayout(panelbtech);
        panelbtech.setLayout(panelbtechLayout);
        panelbtechLayout.setHorizontalGroup(
            panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbtechLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63))
                .addGap(210, 210, 210)
                .addGroup(panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VSMainchk)
                            .addComponent(VISMainchk))
                        .addComponent(VIIISMainchk))
                    .addComponent(VIISMainchk))
                .addGap(223, 223, 223)
                .addGroup(panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VIISBackchk)
                    .addComponent(VISBackchk)
                    .addComponent(VSBackchk)
                    .addComponent(VIIISBackchk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addGroup(panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VISRbchk, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VSRbchk, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VIISRbchk, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VIIISRbchk, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(64, 64, 64))
        );
        panelbtechLayout.setVerticalGroup(
            panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbtechLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel60)
                    .addComponent(VSMainchk)
                    .addComponent(VSBackchk, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VSRbchk, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbtechLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel62)
                            .addComponent(VISMainchk)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbtechLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VISBackchk, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VISRbchk, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(35, 35, 35)
                .addGroup(panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel61)
                    .addComponent(VIISRbchk, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VIISBackchk, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VIISMainchk, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(46, 46, 46)
                .addGroup(panelbtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel63)
                    .addComponent(VIIISMainchk)
                    .addComponent(VIIISBackchk)
                    .addComponent(VIIISRbchk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updateDataBtn.setText("Update");
        updateDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDataBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelmtechLayout = new javax.swing.GroupLayout(panelmtech);
        panelmtech.setLayout(panelmtechLayout);
        panelmtechLayout.setHorizontalGroup(
            panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmtechLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelmtechLayout.createSequentialGroup()
                        .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55)
                            .addComponent(jLabel56)
                            .addComponent(jLabel54))
                        .addGap(212, 212, 212)
                        .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelmtechLayout.createSequentialGroup()
                                .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IISMainchk)
                                    .addComponent(IIISMainchk)
                                    .addComponent(IVSMainchk))
                                .addGap(225, 225, 225)
                                .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(IIISBackchk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(IISBackchk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(IVSBackchk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelmtechLayout.createSequentialGroup()
                                .addComponent(ISMainchk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ISBackchk)
                                .addGap(189, 189, 189)))
                        .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ISRbchk)
                            .addComponent(IISRbchk)
                            .addComponent(IIISRbchk)
                            .addComponent(IVSRbchk))
                        .addGap(75, 75, 75))
                    .addGroup(panelmtechLayout.createSequentialGroup()
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(jLabel58)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addComponent(jLabel53)
                        .addGap(147, 147, 147)
                        .addComponent(jLabel59)
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmtechLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(251, 251, 251))
            .addGroup(panelmtechLayout.createSequentialGroup()
                .addComponent(panelbtech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelmtechLayout.setVerticalGroup(
            panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmtechLayout.createSequentialGroup()
                .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(updateDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmtechLayout.createSequentialGroup()
                        .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54)
                            .addComponent(ISMainchk)
                            .addComponent(ISBackchk))
                        .addGap(34, 34, 34))
                    .addGroup(panelmtechLayout.createSequentialGroup()
                        .addComponent(ISRbchk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56)
                    .addComponent(IISMainchk)
                    .addComponent(IISBackchk)
                    .addComponent(IISRbchk))
                .addGap(29, 29, 29)
                .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelmtechLayout.createSequentialGroup()
                        .addComponent(IIISRbchk)
                        .addGap(42, 42, 42)
                        .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IVSRbchk)
                            .addComponent(IVSBackchk)))
                    .addGroup(panelmtechLayout.createSequentialGroup()
                        .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57)
                            .addComponent(IIISBackchk))
                        .addGap(38, 38, 38)
                        .addGroup(panelmtechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel55)
                            .addComponent(IVSMainchk)))
                    .addComponent(IIISMainchk))
                .addGap(18, 18, 18)
                .addComponent(panelbtech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(panelmtech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelmtech, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(644, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1150, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Marksheets", jPanel1);

        jLabel64.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel64.setText("Issued");

        jLabel65.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel65.setText("Degree");

        jLabel66.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel66.setText("Documents");

        jLabel67.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel67.setText("Provisional certificate");

        degchk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degchkActionPerformed(evt);
            }
        });

        procertychk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procertychkActionPerformed(evt);
            }
        });

        updateDataBtn1.setText("Update");
        updateDataBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDataBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(156, 156, 156)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(procertychk)
                            .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(degchk)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(updateDataBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(426, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(updateDataBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(jLabel66))
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(degchk))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel67)
                    .addComponent(procertychk))
                .addContainerGap(1597, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Degree", jPanel2);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/toy/anagrams/lib/project image/lbwall.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(565, 565, 565)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addGap(500, 500, 500))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
existingstudentexam elog=new existingstudentexam();
examsectiondetail.this.setVisible(false);
elog.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
page1 page=new page1();
examsectiondetail.this.setVisible(false);
page.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDataBtnActionPerformed
        // TODO add your handling code here:
                        
        String sqlExamDetailsUpdate =null;
        int ISMainValue=0;
        int ISBackValue=0;
        int ISRbValue=0;
        int IISMainValue=0;
        int IISBackValue=0;
        int IISRbValue=0;
        int IIISMainValue=0;
        int IIISBackValue=0;
        int IIISRbValue=0;
        int IVSMainValue=0;
        int IVSBackValue=0;
        int IVSRbValue=0;
        int VSMainValue=0;
        int VSBackValue=0;
        int VSRbValue=0;
        int VISMainValue=0;
        int VISBackValue=0;
        int VISRbValue=0;
        int VIISMainValue=0;
        int VIISBackValue=0;
        int VIISRbValue=0;
        int VIIISMainValue=0;
        int VIIISBackValue=0;
        int VIIISRbValue=0;
        if(ISMainchk.isSelected()){
            ISMainValue =1;
        }
        if(ISBackchk.isSelected()){
            ISBackValue=1;
        }
        if(ISRbchk.isSelected()){
            ISRbValue = 1;
        }
        if(IISMainchk.isSelected()){
            IISMainValue =1;
        }
        if(IISBackchk.isSelected()){
            IISBackValue=1;
        }
        if(IISRbchk.isSelected()){
            IISRbValue = 1;
        }
        if(IIISMainchk.isSelected()){
            IIISMainValue =1;
        }
        if(IIISBackchk.isSelected()){
            IIISBackValue=1;
        }
        if(IIISRbchk.isSelected()){
            IIISRbValue = 1;
        }
        if(IVSMainchk.isSelected()){
            IVSMainValue =1;
        }
        if(IVSBackchk.isSelected()){
            IVSBackValue=1;
        }
        if(IVSRbchk.isSelected()){
            IVSRbValue = 1;
        }
        //-----------------------------------------
        //----------Check box chacking for btech-----
        if(course.equals("btech")){
            if(VSMainchk.isSelected()){
                VSMainValue =1;
            }
            if(VSBackchk.isSelected()){
                VSBackValue=1;
            }
            if(VSRbchk.isSelected()){
                VSRbValue = 1;
            }
            if(VISMainchk.isSelected()){
                VISMainValue =1;
            }
            if(VISBackchk.isSelected()){
                VISBackValue=1;
            }
            if(VISRbchk.isSelected()){
                VISRbValue = 1;
            }
            if(VIISMainchk.isSelected()){
                VIISMainValue =1;
            }
            if(VIISBackchk.isSelected()){
                VIISBackValue=1;
            }
            if(VIISRbchk.isSelected()){
                VIISRbValue = 1;
            }
            if(VIIISMainchk.isSelected()){
                VIIISMainValue =1;
            }
            if(VIIISBackchk.isSelected()){
                VIIISBackValue=1;
            }
            if(VIIISRbchk.isSelected()){
                VIIISRbValue = 1;
            }
            sqlExamDetailsUpdate = "UPDATE `btechexamdetail` SET  "
            + "`IS_Main`='"+ISMainValue+"', `IS_Back`='"+ISBackValue+"', `IS_Rb`='"+ISRbValue+"', "
            + "`IIS_Main`='"+IISMainValue+"', `IIS_Back`='"+IISBackValue+"', `IIS_Rb`='"+IISRbValue+"', "
            + "`IIIS_Main`='"+IIISMainValue+"', `IIIS_Back`='"+IIISBackValue+"', `IIIS_Rb`='"+IIISRbValue+"', "
            + "`IVS_Main`='"+IVSMainValue+"', `IVS_Back`='"+IVSBackValue+"', `IVS_Rb`='"+IVSRbValue+"', "
            + "`VS_Main`='"+VSMainValue+"', `VS_Back`='"+VSBackValue+"', `VS_Rb`='"+VSRbValue+"', "
            + "`VIS_Main`='"+VISMainValue+"', `VIS_Back`='"+VISBackValue+"', `VIS_Rb`='"+VISRbValue+"', "
            + "`VIIS_Main`='"+VIISMainValue+"', `VIIS_Back`='"+VIISBackValue+"', `VIIS_Rb`='"+VIISRbValue+"', "
            + "`VIIIS_Main`='"+VIIISMainValue+"', `VIIIS_Back`='"+VIIISBackValue+"', `VIIIS_Rb`='"+VIIISRbValue+"'"
            + "WHERE `Scholar`='"+scholarId+"'";
            System.out.println(sqlExamDetailsUpdate);
        }
        else{
            sqlExamDetailsUpdate = "UPDATE `mtechexamdetail` SET  "
            + "`IS_Main`='"+ISMainValue+"', `IS_Back`='"+ISBackValue+"', `IS_Rb`='"+ISRbValue+"', "
            + "`IIS_Main`='"+IISMainValue+"', `IIS_Back`='"+IISBackValue+"', `IIS_Rb`='"+IISRbValue+"', "
            + "`IIIS_Main`='"+IIISMainValue+"', `IIIS_Back`='"+IIISBackValue+"', `IIIS_Rb`='"+IIISRbValue+"', "
            + "`IVS_Main`='"+IVSMainValue+"', `IVS_Back`='"+IVSBackValue+"', `IVS_Rb`='"+IVSRbValue+"'"
            + "WHERE `Scholar`='"+scholarId+"'";
            System.out.println(sqlExamDetailsUpdate);
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/details","root","");
            Statement stmt=con.createStatement();

        //stmt.execute(selectQuery);
            stmt.executeUpdate(sqlExamDetailsUpdate);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(examsectiondetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(examsectiondetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updateDataBtnActionPerformed

    private void VSRbchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VSRbchkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VSRbchkActionPerformed

    private void ISRbchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISRbchkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISRbchkActionPerformed

    private void ISBackchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBackchkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISBackchkActionPerformed

    private void IISMainchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IISMainchkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IISMainchkActionPerformed

    private void ISMainchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISMainchkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ISMainchkActionPerformed

    private void degchkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degchkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_degchkActionPerformed

    private void procertychkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procertychkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procertychkActionPerformed

    private void updateDataBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDataBtn1ActionPerformed
        // TODO add your handling code here:
        int degreeValue=0;
        int procertyValue=0;
        if(degchk.isSelected()){
            degreeValue=1;
        }
        if(procertychk.isSelected()){
            procertyValue = 1;
        }
        String updateSql = "UPDATE `"+course+"examdetail` SET  "
            + "`Degree`='"+degreeValue+"', `ProCerti`='"+procertyValue+"'"
            + "WHERE `Scholar`='"+scholarId+"'";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/details","root","");
            Statement stmt=con.createStatement();
            System.out.println(updateSql);
        //stmt.execute(selectQuery);
            stmt.executeUpdate(updateSql);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(examsectiondetail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(examsectiondetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateDataBtn1ActionPerformed
    
    public void getDetail() throws ClassNotFoundException, SQLException{
        
        if(course.equals("mtech"))
        {
            panelbtech.removeAll();
           // System.out.println(panelbtech.isVisible());
        }
        String tbnm=course+"examdetail";
        String selectQuery = "SELECT * FROM "+tbnm+" WHERE Scholar='"+scholarId+"'";
        
        Class.forName("com.mysql.jdbc.Driver");
			Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/details","root","");
			Statement stmt=con.createStatement();
                    //    String selectQuery = "SELECT * FROM ? examdetail WHERE Scholar=?;
	//PreparedStatement pstmt=con.prepareStatement();
			//stmt.execute(selectQuery);
                        ResultSet rs = stmt.executeQuery(selectQuery);
                        while(rs.next())
                        {
                        
                         boolean IS_Main = rs.getBoolean("IS_Main");
                         System.out.println(IS_Main);
                         if(IS_Main){
                             ISMainchk.setSelected(true);
                         }
                         boolean IS_Back = rs.getBoolean("IS_Back");
                         //System.out.println(IS_Back);
                         if(IS_Back){
                             
                             ISBackchk.setSelected(true);
                         }
                         boolean IS_Rb = rs.getBoolean("IS_Rb");
                         if(IS_Rb){
                             ISRbchk.setSelected(true);
                         }
                         boolean IIS_Main = rs.getBoolean("IIS_Main");
                         if(IIS_Main){
                             IISMainchk.setSelected(true);
                         }
                         boolean IIS_Back = rs.getBoolean("IIS_Back");
                         if(IIS_Back){
                             IISBackchk.setSelected(true);
                         }
                         boolean IIS_Rb = rs.getBoolean("IIS_Rb");
                         if(IIS_Rb){
                             IISRbchk.setSelected(true);
                         }
                         boolean IIIS_Main = rs.getBoolean("IIIS_Main");
                         if(IIIS_Main){
                             IISMainchk.setSelected(true);
                         }
                         boolean IIIS_Back= rs.getBoolean("IIIS_Back");
                         if(IIIS_Back){
                             IIISBackchk.setSelected(true);
                         }
                         boolean IIIS_Rb = rs.getBoolean("IIIS_Rb");
                         if(IIIS_Rb){
                             IIISRbchk.setSelected(true);
                         }
                         boolean IVS_Main = rs.getBoolean("IVS_Main");
                         if(IVS_Main){
                             IVSMainchk.setSelected(true);
                         }
                         boolean IVS_Back = rs.getBoolean("IVS_Back");
                         if(IVS_Back){
                             IVSBackchk.setSelected(true);
                         }
                         boolean IVS_Rb = rs.getBoolean("IVS_Rb");
                         if(IVS_Rb){
                             IVSRbchk.setSelected(true);
                         }
                         boolean Degree=rs.getBoolean("Degree");
                          if(Degree){
                              degchk.setSelected(true);
                          }
                          boolean ProCerti=rs.getBoolean("ProCerti");
                          if(ProCerti){
                              procertychk.setSelected(true);
                          }
                        if(course.equals("btech"))
                        {
                         boolean VS_Main = rs.getBoolean("VS_Main");
                          if(VS_Main){
                             VSMainchk.setSelected(true);
                          }
                         boolean VS_Back = rs.getBoolean("VS_Back");
                          if(VS_Back){
                             VSBackchk.setSelected(true);
                          }
                         boolean VS_Rb = rs.getBoolean("VS_Rb");
                          if(VS_Rb){
                             VSRbchk.setSelected(true);
                          }
                         boolean VIS_Main = rs.getBoolean("VIS_Main");
                          if(VIS_Main){
                             VISMainchk.setSelected(true);
                          }
                         boolean VIS_Back = rs.getBoolean("VIS_Back");
                          if(VIS_Back){
                             VISBackchk.setSelected(true);
                          }
                         boolean VIS_Rb = rs.getBoolean("VIS_Rb");
                          if(VIS_Rb){
                             VISRbchk.setSelected(true);
                          }
                         boolean VIIS_Main = rs.getBoolean("VIIS_Main");
                          if(VIIS_Main){
                             VIISMainchk.setSelected(true);
                          }
                         boolean VIIS_Back = rs.getBoolean("VIIS_Back");
                          if(VIIS_Back){
                             VIISBackchk.setSelected(true);
                          }
                         boolean VIIS_Rb = rs.getBoolean("VIIS_Rb");
                          if(VIIS_Rb){
                             VIISRbchk.setSelected(true);
                          }
                         boolean VIIIS_Main = rs.getBoolean("VIIIS_Main");
                          if(VIIIS_Main){
                             VIIISMainchk.setSelected(true);
                          }
                         boolean VIIIS_Back = rs.getBoolean("VIIIS_Back");
                          if(VIIIS_Back){
                             VIIISBackchk.setSelected(true);
                          }
                         boolean VIIIS_Rb = rs.getBoolean("VIIIS_Rb");
                          if(VIIIS_Rb){
                             VIIISRbchk.setSelected(true);
                          }                          
                        // System.out.println(degtxt.getText()+"\n"+pctext.getText());
                        }
}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(examsectiondetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(examsectiondetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(examsectiondetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(examsectiondetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        course =args[0];
        scholarId = args[1];
        System.out.println(course+"\t"+scholarId);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new examsectiondetail().setVisible(true);//new examsectiondetail.chk.setText("dfhfgjh");
                try {
                    examsectiondetail ex = new examsectiondetail();
                    ex.setVisible(true);
                    ex.getDetail();
                    
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(examsectiondetail.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(examsectiondetail.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox IIISBackchk;
    private javax.swing.JCheckBox IIISMainchk;
    private javax.swing.JCheckBox IIISRbchk;
    private javax.swing.JCheckBox IISBackchk;
    private javax.swing.JCheckBox IISMainchk;
    private javax.swing.JCheckBox IISRbchk;
    private javax.swing.JCheckBox ISBackchk;
    private javax.swing.JCheckBox ISMainchk;
    private javax.swing.JCheckBox ISRbchk;
    private javax.swing.JCheckBox IVSBackchk;
    private javax.swing.JCheckBox IVSMainchk;
    private javax.swing.JCheckBox IVSRbchk;
    private javax.swing.JCheckBox VIIISBackchk;
    private javax.swing.JCheckBox VIIISMainchk;
    private javax.swing.JCheckBox VIIISRbchk;
    private javax.swing.JCheckBox VIISBackchk;
    private javax.swing.JCheckBox VIISMainchk;
    private javax.swing.JCheckBox VIISRbchk;
    private javax.swing.JCheckBox VISBackchk;
    private javax.swing.JCheckBox VISMainchk;
    private javax.swing.JCheckBox VISRbchk;
    private javax.swing.JCheckBox VSBackchk;
    private javax.swing.JCheckBox VSMainchk;
    private javax.swing.JCheckBox VSRbchk;
    private javax.swing.JCheckBox degchk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelbtech;
    private javax.swing.JPanel panelmtech;
    private javax.swing.JCheckBox procertychk;
    private javax.swing.JButton updateDataBtn;
    private javax.swing.JButton updateDataBtn1;
    // End of variables declaration//GEN-END:variables
    private static String course;
    private static String scholarId;
}
